---
title: 3D sleutelhanger
hero_image: images/banner.png
description: Ontwerp een CODER-sleutelhanger die 3D geprint kan worden.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: What you will make
  - 
    title: Maak 3D-tekst
    completion:
      - engaged
  - 
    title: Change thickness
  - 
    title: Save your project
    completion:
      - internal
  - 
    title: Challenges
    chalenge: true
  - 
    title: 3D print your key ring
  - 
    title: Assemble your key ring
    completion:
      - external
