title: 3D printable keyring
hero_image: images/banner.png
description: blockscad-coder-keyring description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
steps:
  - title: Introduction
  - title: Creating 3D text
  - title: Joining letters together
  - title: Alternating height
  - title: Saving
  - title: Challenges
  - title: 3D printing 
  - title: Keyring assembly
