title: 3D printable key ring
hero_image: images/banner.png
description: blockscad-coder-keyring description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
steps:
  - title: Introduction
  - title: Create 3D text
  - title: Join the letters together
  - title: Change thickness
  - title: Save your project
  - title: Challenges
  - title: 3D print your key ring
  - title: Assemble your key ring
