---
title: 3D चाबी का छल्ला
hero_image: images/banner.png
description: एक CODER चाबी का छल्ला डिज़ाइन करें जो 3D प्रिंट की जा सकती है।
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: What you will make
  - 
    title: 3D टेक्स्ट बनाये
    completion:
      - engaged
  - 
    title: Change thickness
  - 
    title: Save your project
    completion:
      - internal
  - 
    title: Challenges
    chalenge: true
  - 
    title: 3D print your key ring
  - 
    title: Assemble your key ring
    completion:
      - external
