---
title: 3Dキーホルダー
hero_image: images/banner.png
description: 3Dプリントできる「CODER」(コーダー) キーホルダーを設計 (せっけい) しよう
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
- title: はじめに
  completion: engaged
- title: 3Dテキストを作る
- title: 文字をつなげる
- title: 厚さ (あつさ) をかえる
- title: プロジェクトを保存 (ほぞん) する
- title: チャレンジ
- title: キーホルダーを3Dプリントする
  completion: internal
- title: キーホルダーを組み立てる
