---
title: 3D key ring
hero_image: images/banner.png
description: Design a CODER keyring that can be 3D printed.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: Introduction
  - 
    title: Create 3D text
  - 
    title: Join the letters together
    completion:
      - engaged
  - 
    title: Change thickness
  - 
    title: Save your project
  - 
    title: Challenges
  - 
    title: 3D print your key ring
  - 
    title: Assemble your key ring
    completion:
      - internal
