---
title: Llavero 3D
hero_image: images/banner.png
description: Diseña un llavero con las letras "CODER" que se pueda imprimir en 3D.
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: Introducción
  - 
    title: Crear texto en 3D
  - 
    title: Pon las letras juntas
  - 
    title: Cambiar de grosor
  - 
    title: Guarda tu proyecto
  - 
    title: Desafíos
  - 
    title: Imprime tu llavero en 3D
  - 
    title: Monta tu llavero
