---
title: 3D-Schlüsselanhänger
hero_image: images/banner.png
description: Entwirf einen 'CODER'-Schlüsselanhänger, der in 3D gedruckt werden kann.
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: Einleitung
  - 
    title: Erstelle den 3D-Text
  - 
    title: Verbinde die Buchstaben miteinander
  - 
    title: Ändere die Dicke
  - 
    title: Speichere dein Projekt
  - 
    title: Herausforderungen
  - 
    title: Drucke deinen Schlüsselanhänger in 3D
  - 
    title: Baue deinen Schlüsselanhänger zusammen
