---
title: 3D-Schlüsselanhänger
hero_image: images/banner.png
description: Entwirf einen 'CODER'-Schlüsselanhänger, der in 3D gedruckt werden kann.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: What you will make
  - 
    title: Erstelle den 3D-Text
    completion:
      - engaged
  - 
    title: Change thickness
  - 
    title: Save your project
    completion:
      - internal
  - 
    title: Challenges
    chalenge: true
  - 
    title: 3D print your key ring
  - 
    title: Assemble your key ring
    completion:
      - external
