---
title: Chaveiro 3D
hero_image: images/banner.png
description: Crie um chaveiro 'CODER' que possa ser impresso em 3D.
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: Introdução
  - 
    title: Criar texto 3D
  - 
    title: Junte as letras
  - 
    title: Altere a espessura
  - 
    title: Salve seu projeto
  - 
    title: Desafios
  - 
    title: Imprima em 3D seu chaveiro
  - 
    title: Monte seu chaveiro
