---
title: Chaveiro 3D
hero_image: images/banner.png
description: Crie um chaveiro 'CODER' que possa ser impresso em 3D.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
- title: Introdução
  completion: engaged
- title: Criar texto 3D
- title: Junte as letras
- title: Altere a espessura
- title: Salve seu projeto
- title: Desafios
- title: Imprima em 3D seu chaveiro
  completion: internal
- title: Monte seu chaveiro
