---
title: Llavero 3D
hero_image: images/banner.png
description: Diseña un llavero con las letras "CODER" que se pueda imprimir en 3D.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: Introducción
  - 
    title: Crea texto en 3D
  - 
    title: Junta las letras
    completion:
      - engaged
  - 
    title: Cambia el grosor
  - 
    title: Guarda tu proyecto
  - 
    title: Desafíos
  - 
    title: Imprime tu llavero en 3D
  - 
    title: Arma tu llavero
    completion:
      - internal
