---
title: Llavero 3D
hero_image: images/banner.png
description: Diseña un llavero con las letras "CODER" que se pueda imprimir en 3D.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: What you will make
  - 
    title: Crea texto en 3D
    completion:
      - engaged
  - 
    title: Change thickness
  - 
    title: Save your project
    completion:
      - internal
  - 
    title: Challenges
    chalenge: true
  - 
    title: 3D print your key ring
  - 
    title: Assemble your key ring
    completion:
      - external
