---
title: حلقة مفاتيح ثلاثية الابعاد (3D)
hero_image: images/banner.png
description: تصميم حلقة مفاتيح (CODER) التي يمكن طباعتها بشكل ثلاثي الأبعاد.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: المقدمة
  - 
    title: إنشاء نص ثلاثي الأبعاد
  - 
    title: ربط الحروف مع بعضها البعض
    completion:
      - engaged
  - 
    title: تغيير السماكة
  - 
    title: احفظ مشروعك
  - 
    title: التحديات
  - 
    title: اطبع حلقة مفاتيحك بشكل ثلاثي الابعاد
  - 
    title: تجميع حلقة المفاتيح الخاصة بك
    completion:
      - internal
