---
title: حلقة مفاتيح ثلاثية الابعاد (3D)
hero_image: images/banner.png
description: تصميم حلقة مفاتيح (CODER) التي يمكن طباعتها بشكل ثلاثي الأبعاد.
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: المقدمة
  - 
    title: إنشاء نص ثلاثي الأبعاد
  - 
    title: ربط الحروف مع بعضها البعض
  - 
    title: Change thickness
  - 
    title: Save your project
  - 
    title: Challenges
  - 
    title: 3D print your key ring
  - 
    title: Assemble your key ring
