---
title: حلقة مفاتيح ثلاثية الابعاد (3D)
hero_image: images/banner.png
description: تصميم حلقة مفاتيح (CODER) التي يمكن طباعتها بشكل ثلاثي الأبعاد.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: What you will make
  - 
    title: إنشاء نص ثلاثي الأبعاد
    completion:
      - engaged
  - 
    title: Change thickness
  - 
    title: Save your project
    completion:
      - internal
  - 
    title: Challenges
    chalenge: true
  - 
    title: 3D print your key ring
  - 
    title: Assemble your key ring
    completion:
      - external
