---
title: حلقة مفاتيح ثلاثية الابعاد (3D)
hero_image: images/banner.png
description: تصميم حلقة مفاتيح (CODER) التي يمكن طباعتها بشكل ثلاثي الأبعاد.
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
steps:
- title: المقدمة
  completion: engaged
- title: إنشاء نص ثلاثي الأبعاد
- title: ربط الحروف مع بعضها البعض
- title: تغيير السماكة
- title: احفظ مشروعك
- title: التحديات
- title: اطبع حلقة مفاتيحك بشكل ثلاثي الابعاد
  completion: internal
- title: تجميع حلقة المفاتيح الخاصة بك
