---
title: Porte-clés 3D
hero_image: images/banner.png
description: Conçois un porte-clés CODER qui peut être imprimé en 3D.
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
steps:
  - 
    title: Introduction
  - 
    title: Créer un texte 3D
  - 
    title: Relier les lettres ensemble
  - 
    title: Changer l'épaisseur
  - 
    title: Enregistre ton projet
  - 
    title: Défis
  - 
    title: Imprime ton porte-clés en 3D
  - 
    title: Assembler ton porte-clés
